### ISSUE TITLE
Selecting only a number and operator will cause a FormatException when calculating the result

### ISSUE THREAD

**Issue by murrty** [AlperAkca79/dotNETCalculator#1]
I saw your reddit post, neat project. I wanted to check it out, so I cloned it and did some testing. I found an immediate issue.

If you select a first number (let's say 9), an operator (let's say add) and immediate go to calculate the result, a FormatException will occur at this line:

https://github.com/AlperAkca79/dotNETCalculator/blob/05ccae288a6bf4ffd85888e0754e30ac3705d44a/dotNETCalculator/MainWindow.xaml.cs#L212

While I could implement a safer way to patch it up, a very quick and dirty work around would be to change it to

    if (string.IsNullOrWhiteSpace(output))
        output = temp.ToString();
    
    PreviewOutput.Text = (temp.ToString() + " " + operation + " " + double.Parse(output) + " " + "=");
    ...

A default behavior could be that the input value should be subject to both sides of the calculation when doing (basic) operations. That way, 9+= would be 9+9=18.

**Comment by fjord79** [comment]
@murrty Thanks for reporting this issue and fixing code at line 212.
